# Generated by Django 4.2.4 on 2023-08-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
