# Generated by Django 4.2.4 on 2023-09-09 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_remove_task_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.house'),
        ),
        migrations.AlterField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(related_name='task_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
