# Generated by Django 4.2.4 on 2023-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_assigned_to_taskinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('TO DO', 'To do')], default='TO DO', max_length=32),
        ),
    ]
