# Generated by Django 4.2.4 on 2023-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_taskinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='completed_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
